### ISSUE TITLE
Deployment sometimes fails with a 404 error

### ISSUE THREAD

**Issue by sandrinodimattia** [auth0-extensions/auth0-bitbucket-deploy#7]
The Bitbucket API client should at least log why it is failing (in the progress logs)

**Comment by AmaanC** [comment]
It seems to _always_ fail with a 404 error for me.

All I did to reproduce was
- Create a new tenant
- Create a new Bitbucket repo
- Install the extension and configure it
- Try to deploy

Trying the API directly seems to work fine for me, so I'm not sure where the problem lies.

**Comment by AmaanC** [comment]
Alright, so here's the issue. For missing directories, we `resolve` based on the `err.message` [here](https://github.com/auth0-extensions/auth0-bitbucket-deploy/blob/c83c39ac8923a399932720be30ae9535243ce07c/server/lib/bitbucket.js#L179) (and in several other places, for all the other requests as well.)
However, the actual error that _will_ be thrown [here](https://github.com/auth0-extensions/auth0-bitbucket-deploy/blob/53a9a872d98552b5ae46091e70f9d769831a9240/server/lib/bitbucketApi.js#L73) is `Bitbucket Api - Status Code: 404`.
Since the `err.message` doesn't match, we will always `reject`, causing the deploy to fail.

Quickfix would be to change the `err.message` in either of those files to match up with the other.
